device: cpu # 强制使用CPU
weights:
  doclayout_yolo: Structure/doclayout_yolo_docstructbench_imgsz1280_2501.pt
  layoutreader: Relation
models_dir: model_weight
layout_config: 
  model: doclayout_yolo
  reader:
    name: layoutreader
chat_config:
  weight_path: model_weight/Recognition
  backend: transformers # 使用transformers后端，更适合CPU
  batch_size: 1 # CPU模式下减少批处理大小 