repos:
  # Python代码格式化和检查
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.9
        files: ^file_processing_website/backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^file_processing_website/backend/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^file_processing_website/backend/

  # 前端代码格式化和检查
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^file_processing_website/frontend/
        types_or: [javascript, typescript, vue, json, yaml, markdown]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.2
    hooks:
      - id: eslint
        files: ^file_processing_website/frontend/.*\.(js|ts|vue)$
        additional_dependencies:
          - eslint@^9.0.0
          - eslint-plugin-vue@^10.0.0

  # 通用检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10240']  # 10MB

  # 安全检查
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^file_processing_website/backend/
        args: ['-r', '.']
        exclude: ^file_processing_website/backend/tests/

  # Docker文件检查
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: ^file_processing_website/docker/Dockerfile.* 